spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Practics
    username: postgres
    password: 8526


  liquibase:
    change-log: db/changelog/main-changelog.xml
